### ISSUE TITLE
Loggin first

### ISSUE THREAD

**Issue by Tozapid** [anonymous1184/bitwarden-autotype#1]
Hi!
Every time I try to connect, it says, "Loggin first." But BW CLI works perfectly.

```
C:\bitwarden-autotype\bw.exe -v
1.9.1
```

**Comment by anonymous1184** [comment]
Hey!

Thank you for reporting, turns out it was a bug (and a typo). The current release ([20.04.07](https://github.com/anonymous1184/bitwarden-autotype/releases/tag/20.04.07)) fixes both.

Stay safe
