### ISSUE TITLE
PIN options

### ISSUE THREAD

**Issue by Nypheena** [anonymous1184/bitwarden-autotype#11]
first I'd like to start off, any chance to reduce the pin length to 4? ideally let people choose length

and even if adding 2fa to it, still keeps asking for master password

**Comment by anonymous1184** [comment]
Thanks for the feature suggestion, is added in the latest release. However for security any length below 4 is not allowed and even a 4-digit PIN is not recommended at all.

[PIN number analysis](https://www.datagenetics.com/blog/september32012/)
