### ISSUE TITLE
Suddendly getting: "Your authentication request appears to be coming from a bot." error after logging in 

### ISSUE THREAD

**Issue by nefrog** [anonymous1184/bitwarden-autotype#13]
I think Bitwarden broke this amazing script :(

**Comment by anonymous1184** [comment]
Seems to be an issue of an alarming number of wrong passwords. I haven't seen this but documentation states that you can avoid the issue via API keys.

I'll see to add this as an option in the advanced settings.

**Comment by anonymous1184** [comment]
I'm working on the fix, but even with a ridiculous amount of bad passwords and/or email/authenticator codes I cannot trigger the error.

Do you mind to share your location? Perhaps this is location-based. Do you have enabled any Two-Step Login method? Perhaps this is only triggered when no Two-Step verification is done.

**Comment by nefrog** [comment]
I'm in Canada. I originally did not have 2fa for this application. With 2fa now enabled the error no longer pops up.

**Comment by TSnatch72** [comment]
so there's no way to place the api key in say, the settings json file, right now?
