### ISSUE TITLE
[Enhancement] Restore previous clipboard value

### ISSUE THREAD

**Issue by KnightTim** [anonymous1184/bitwarden-autotype#17]
When putting a TOTP code in the clipboard save the previous value in the clipboard and after 30sec (when the TOTP is no longer valid) restore the previous clipboard value.

**Comment by anonymous1184** [comment]
While doable it shouldn't be forced to 30 seconds even if the vast majority of Key Uris use the 30 second default [period][1], a more sensible approach is to use as timeout the period in the Key Uri (or the default if missing).

The TOTP algorithm uses [floor divide][2] to get the time counter, so for the Clipboard should be restored when the current second is either `0` or matches the period.

[1]: https://github.com/google/google-authenticator/wiki/Key-Uri-Format#period
[2]: https://datatracker.ietf.org/doc/html/rfc6238#section-4.2
