### ISSUE TITLE
Setup.ahk fails install

### ISSUE THREAD

**Issue by Oxika95** [anonymous1184/bitwarden-autotype#23]
![image](https://user-images.githubusercontent.com/48342370/154115402-a9956d94-a937-46ae-be7e-6730856348fc.png)

**Comment by anonymous1184** [comment]
The project has already pre-built binaries from where you can either run it in portable mode (`bw-at.exe`) or use the installer (`setup.exe`), the later does everything it needs automatically and AutoType can works in applications with higher integrity ([UIPI][1]):

<https://github.com/anonymous1184/bitwarden-autotype/releases/latest>

The `setup.ahk` is meant to create the installer, not directly install.

If you don't want to use the pre-built binaries  and you have experience with AutoHotkey you can manually run `bw-at.ahk`, the other option is to build your own binaries by using the `build.ahk` script.

[1]: https://en.wikipedia.org/wiki/User_Interface_Privilege_Isolation
