### ISSUE TITLE
AutoType wont get URL from Opera GX

### ISSUE THREAD

**Issue by TheBluuDot** [anonymous1184/bitwarden-autotype#24]
AutoType cannot seem to get the URL from the Opera GX process `opera.exe`. The browser version is LVL3 (core: 83.0.4254.70).

![image](https://user-images.githubusercontent.com/62665768/155838980-2d1f8e5a-3f3a-445b-a4d3-a6a0f1224d8a.png)

**Comment by anonymous1184** [comment]
Never knew there was an specialized version of Opera for gaming. If it still is Chromium-based most likely is just extra object(s) matching the Address Bar given how Opera tends to overcrowd UIs.

I'll add the support and release as another build from the current release.

Thanks for the report!

**Comment by TheBluuDot** [comment]
You're welcome and thanks a lot for adding support!

**Comment by anonymous1184** [comment]
Current release ([v1.1.4][1]) has now updated assets with support for Opera GX.

[1]: https://github.com/anonymous1184/bitwarden-autotype/releases/tag/v1.1.4
