### ISSUE TITLE
[question] what is bw-at.bin in assets?

### ISSUE THREAD

**Issue by errdos** [anonymous1184/bitwarden-autotype#31]
looking at the readme and going over the git log couldn't understand what is the asset bw-at.bin?
is it needed? what is it used for?

thanks for the great tool :)  trying to understand it a bit.

**Comment by anonymous1184** [comment]
Thanks for your interest in the source, glad to clear any concern!

AutoHotkey is not a compiled programming language but an interpreted scripting language. When "building" from source what it really does is to attach the script to an interpreter via `Ahk2Exe.exe`.

That file is the same as `Unicode 64-bit.bin` found in the AutoHotkey distribution, is only "optimized" (if the small changes I made can be labeled somehow). It been stripped a few assets: a menu, the accelerators and the icons the Auto-Type application won't need (AutoHotkey's built-in).

The `Ahk2Exe.exe` knows that it needs to use this specific file for the final executable as is defined via a [Script Compiler Directive][1] in the code:

https://github.com/anonymous1184/bitwarden-autotype/blob/408bb6d72e5186be2709411f8c486f03d9a7165f/bw-at.ahk#L186

[1]: https://www.autohotkey.com/docs/misc/Ahk2ExeDirectives.htm#Bin

Hope is more clear now.
