### ISSUE TITLE
Shift-Tab?

### ISSUE THREAD

**Issue by DocMAX** [anonymous1184/bitwarden-autotype#36]
Hi, i need to go to a previous field and added "{LShift}+{Tab}" at the beginning, but this doesn't work. How can i make it work?
`{LShift}+{Tab}{ClearField}{Username}{SmartTab}{Password}{SmartTab}pass{Enter}`

**Comment by anonymous1184** [comment]
The proper syntax would be:

`+{Tab}{ClearField}{Username}{SmartTab}{Password}{SmartTab}pass{Enter}`
