### ISSUE TITLE
Bitwarden CLI repo has been archived

### ISSUE THREAD

**Issue by KnightTim** [anonymous1184/bitwarden-autotype#38]
Bitwarden has changed the way it is handling updates for clients and moved them to a [new repo](https://github.com/bitwarden/clients).
The [old repo](https://github.com/bitwarden/cli) is archived and read-only. 

I recommend changing [Line 155 of the Readme.md](https://github.com/anonymous1184/bitwarden-autotype/blob/e55cca198a280bf85d6e260a6295612a012a636f/README.md?plain=1#L155)
from: 
`[11]: https://github.com/bitwarden/cli "Bitwarden CLI"`
to: 
`[11]: https://github.com/bitwarden/clients/releases?q=cli "Bitwarden CLI"`

The [updated url](https://github.com/bitwarden/clients/releases?q=cli) should take users to the latest BW CLI release.

**Comment by anonymous1184** [comment]
I was browsing the repo when they archived it. Fortunately they leave the old versions in place.

I was away for a couple of months but I'm now back, I have a few ideas for the next release and one of them is account for this change.

As always, thanks for your input
