### ISSUE TITLE
the exe uses 20% cpu

### ISSUE THREAD

**Issue by BigHoss** [anonymous1184/bitwarden-autotype#40]
![image](https://user-images.githubusercontent.com/932436/207005294-f74edab9-ae2c-42af-8ae6-043371661c27.png)

checked on multiple pcs

why would it need that much performance when its not doing anything?

**Comment by anonymous1184** [comment]
Hello @BigHoss 

Thanks for the report, but I haven't been able to replicate.

I've tested the app extensively and never ran into that issue. As a matter of fact, it is used in my workplace for a couple of hundred colleagues (W10/W11).

The only things that cross my mind are either an antivirus making noise or something very peculiar on your database. Would you mind to share more details of your setup and your Bitwarden database?

Here's a 23-second video showing the app with 0.00% of CPU and 4.5Mb of RAM, in my case there are around 500 login entries in a self-hosted vault. No AV software and Microsoft Defender was removed from the installation media:

https://user-images.githubusercontent.com/53758552/207469855-ff283126-b5cb-4f97-ba4e-b326c4b48c03.mp4

When I use the Task Manager it returns 1.5Mb, I'm guessing it reports the compressed memory pages.

![20221213175048](https://user-images.githubusercontent.com/53758552/207470281-bc05ade5-ecc8-4bac-a5fb-7f934defa7cb.png)

![20221213175734](https://user-images.githubusercontent.com/53758552/207471046-868456c1-2304-418c-96ec-53c1252184c8.png)

Also, I'm using the latest version from the GitHub repo.

**Comment by Elrondolio** [comment]
Love Auto-Type, but I too see constant CPU cycles with it on all systems I run it.  Here is an example minute thirty video from my Ryzen 7 5800H, 32GB laptop showing it using 6.3% continuously while "idling" in the background.  This same type of CPU cycles happens on my main PC, my work PC, my wife's laptop, etc... anywhere from 6-20% CPU cycles everywhere I run it.


https://user-images.githubusercontent.com/46227346/210219614-d36ef413-6101-43ca-8ce6-38c6c1b48e97.mp4

**Comment by lesourcil** [comment]
Same issue here.  Always around 10% cpu usage

**Comment by BigHoss** [comment]
As this tool calls a lot of different webplatforms a lot of time it gets sqashed by the antivir. I moved to a different solution (1Password)
