### ISSUE TITLE
dosent work for own installations 

### ISSUE THREAD

**Issue by worryboy** [anonymous1184/bitwarden-autotype#42]
it looks like that only vault.bitwarden.com is supported. Other self managed instalation of Bitwarden or VaultWarden are not supported. 

notes:
1. tested without custom setup 
2. tested to setup own URL via CLi command line 
`bw config server https://vault.myownserver.net`
3. copied data.json from "C:\Users\MyUser\AppData\Roaming\Bitwarden CLI" to "C:\Program Files\Auto-Type"

without success

**Comment by anonymous1184** [comment]
It works, and you don't need the work done in the steps.

You only need to edit the `settings.ini` file and add your server in the `[ADVANCED]` section (around line 202):

```ini
## On-premises Hosting

server =
; https://bitwarden.com/help/article/change-client-environment/#cli

NODE_EXTRA_CA_CERTS =
; https://bitwarden.com/help/article/cli/#using-self-signed-certificates
```
