### ISSUE TITLE
Using Self Hosted Bitwarden

### ISSUE THREAD

**Issue by leanderlist** [anonymous1184/bitwarden-autotype#43]
Hey,
I am self hosting bitwarden on my raspi. Is there a way to use your application. I switched from keepass and autotype is something which I am really missing.
Kind regards leander

**Comment by cpainchaud** [comment]
Hi,

 may be you should have a look here https://github.com/anonymous1184/bitwarden-autotype/issues/42

**Comment by leanderlist** [comment]
Thanks for your reply. Where can I find the settings.ini file?

**Comment by leanderlist** [comment]
Okay I got it thanks for your help. The File is located in C:/Users/USER/AppData/Roaming/Auto-Type

**Comment by leanderlist** [comment]
Okay I got it thanks for your help. The File is located in C:/Users/USER/AppData/Roaming/Auto-Type
