### ISSUE TITLE
Argon2 support

### ISSUE THREAD

**Issue by legolasdimir** [anonymous1184/bitwarden-autotype#47]
After updating my KDF to argon2 I am not able to log into this app. I get a message that says unknown KDF. I know that it uses the bitwarden cli, is this something that I can download an updated version of the CLI to fix?

**Comment by cpainchaud** [comment]
Yeah this project doesn't touch the API at all, the CLI does

**Comment by legolasdimir** [comment]
@cpainchaud i tried to update the app by just downloading the installer again. but it didn't seem to work do I need to manually download the CLI and replace it in the app install?

**Comment by legolasdimir** [comment]
OK, I manually updated the cli from the bitwarden site, and now it works.
