### ISSUE TITLE
Broken install

### ISSUE THREAD

**Issue by Lippiece** [anonymous1184/bitwarden-autotype#48]
It installs with errors and then I have persistent "Please wait..." under my cursor.

**Comment by Lippiece** [comment]
![image](https://user-images.githubusercontent.com/47634624/224552312-ae22700f-be84-4677-af2d-78ad4271e158.png)
Any idea where does it try to install and what processes does it use? I would very much like to get rid of this.

**Comment by anonymous1184** [comment]
> It installs with errors

Which errors, can you please elaborate?

The `Please wait...` under the cursor means that PowerShell never finishes its part of the installation. My best guess is that you have either an Anti-virus that is blocking it from running, or you have restrictions on PowerShell.

**Comment by Lippiece** [comment]
@anonymous1184

<details>
<summary>The errors</summary>


![FMYAHxJIP8](https://user-images.githubusercontent.com/47634624/224559160-c019bf0e-9ef5-41c5-93b8-27acb09374b1.png)
![rNP5siMA1B](https://user-images.githubusercontent.com/47634624/224559181-0b339fc8-92db-4533-9e0d-ce7929458eb6.png)
![lZwE8b5us6](https://user-images.githubusercontent.com/47634624/224559183-cf204907-e0a6-4607-97de-3bbf9f758670.png)


</details>

**Comment by anonymous1184** [comment]
Looks like something is deleting the files needed for the process to complete.

That is only done by an antivirus (it could delete or quarantine), Windows Defender plays nice with Auto-Type.

Are you using a 3rd party antivirus?

**Comment by Lippiece** [comment]
> Looks like something is deleting the files needed for the process to complete.
> 
> That is only done by an antivirus (it could delete or quarantine), Windows Defender plays nice with Auto-Type.
> 
> Are you using a 3rd party antivirus?

I'm using standard Windows settings. Windows also blocked the launch of the setup at the first time.

Can you say what to look for in the Task Manager? "Please wait" makes me crazy.

EDIT: For the ones that will suffer the same consequences of disagreeing with Windows and running the setup, look for "setup.exe" with a Bitwarden logo in "Details" in Task Manager.

**Comment by anonymous1184** [comment]
You seem mad, that is something completely outside my control (or any developer for that matter). Even Microsoft themselves have been victims of false positives.

Looks like you are running Windows 10: here's a video of a clean VM with W10 22H2 (latest updates) and no issues at all. Shows the following:

- Nothing is installed.
- Current status of Defender.
- Quick Defender scan.
  - No detections.
- Download the setup.
- Scan the setup file.
  - No detections.
- Install.
- Quick Defender scan.
  - No detections.
- Uninstall.

https://user-images.githubusercontent.com/53758552/224567224-847742e5-72e7-4a1c-b9e3-887f30e42567.mp4

If you have false positives issues, remember that Defender does collect data and if you are in the habit of downloading stuff that gets flagged (for example game hacks/patches/mods/trainers), Defender will be very aggressive as you have history if high-risk files.

Let me know if I can be of further assistance.

**Comment by HearthCore** [comment]
RunAs Administrator solved the issue for me.

**Comment by Lippiece** [comment]
For some reason it doesn't ask for admin rights and running it as admin solves the issue for me too.
