### ISSUE TITLE
Unknown kdf error

### ISSUE THREAD

**Issue by B-u-r-a-G** [anonymous1184/bitwarden-autotype#50]
I got "Unknown kdf" error while traing to log in. I'm not sure why. Only possible reason that I can come up with is that I'm using Argon2id instead of PBKDF2 but I'm not sure

**Comment by anonymous1184** [comment]
Well, the AutoType application does not mess with anything about the encryption/decryption. All of that is done by the CLI client.

If you are getting errors of that kind, come from the CLI client... have you tried to see if there are issues in the Bitwarden repo?
