### ISSUE TITLE
Unlock via custom pin number doesn't work

### ISSUE THREAD

**Issue by LoserForever88** [anonymous1184/bitwarden-autotype#52]
The app still asks me for master password as if the pin number does not exist.  Each time I modify any settings it will ask for pin number and confirmation as if it's the first time setup.

**Comment by anonymous1184** [comment]
> The app still asks me for master password as if the pin number does not exist.

Not a bug, this is by design.

> Each time I modify any settings it will ask for pin number and confirmation as if it's the first time setup.

If you change the unlock mode, it must ask. Again, this is by design.

**Comment by LoserForever88** [comment]
> > The app still asks me for master password as if the pin number does not exist.
> 
> Not a bug, this is by design.
> 
> > Each time I modify any settings it will ask for pin number and confirmation as if it's the first time setup.
> 
> If you change the unlock mode, it must ask. Again, this is by design.

So, I have to enter the master password each time AutoType is started? Even Bitwarden doesn't require such a step.

I didn't change the mode.  I just leave it as unlock via pin number.  It still keeps asking me for new pin number when I ONLY modify other settings.

Edit: Upon further testing the custom pin does work if you manually lock the vault.  But it always asks for master password each time the app is fired up.

**Comment by anonymous1184** [comment]
> Upon further testing the custom pin does work if you manually lock the vault. But it always asks for master password each time the app is fired up.

Yes. Otherwise, the password should have to be stored by means of Auto-Type, that might potentially loosen the security. The current development version (not public yet) gets rid of that by asking the user, the session (not the password) is then saved in the Windows Credential Manager.

AutoHotkey recently released the version 2.0, the migration has taken some time but should not take much longer for a public release and a completely revamped app, written from scratch.

**Comment by LoserForever88** [comment]
> > Upon further testing the custom pin does work if you manually lock the vault. But it always asks for master password each time the app is fired up.
> 
> Yes. Otherwise, the password should have to be stored by means of Auto-Type, that might potentially loosen the security. The current development version (not public yet) gets rid of that by asking the user, the session (not the password) is then saved in the Windows Credential Manager.
> 
> AutoHotkey recently released the version 2.0, the migration has taken some time but should not take much longer for a public release and a completely revamped app, written from scratch.

Understood.  Thank you for all your hard work.  You perfected Bitwarden so much.
