### ISSUE TITLE
Autorun does not work properly

### ISSUE THREAD

**Issue by LoserForever88** [anonymous1184/bitwarden-autotype#53]
First of all checking autorun in the settings doesn't seem to do anything.  So I tried to create a scheduled task to run this program without admin prompt (i.e. highest privilege), and I found that bt-at.exe was fired up in the task manager.  But the program doesn't not appear in systeam tray, and autofill in other program doesn't work.

It seems that this program needs admin privilege to function properly (idk why it isn't set to run in that way by default) , and I can only get the autofill functions to work properly if I manually start the program and accept the admin prompt. Is there any workaround to make it autorun without admin prompt?

Note: I'm using Windows 10 with latest update.

**Comment by LoserForever88** [comment]
This is so weird.  All of a sudden everything works again.  The default autorun is working again after I rechecking the option, and it doesn't need admin prompt to work now.  Maybe things randomly bugged out idk.  So I close this issue for now.

**Comment by anonymous1184** [comment]
> First of all checking autorun in the settings doesn't seem to do anything.

You need to log off, then log again. That's how auto-run works.

> I tried to create a scheduled task to run this program without admin prompt (i.e. highest privilege)

It does work properly, and there is not a single scenario where the installed version should run elevated.

> and I found that bt-at.exe was fired up in the task manager. But the program doesn't not appear in systeam tray, and autofill in other program doesn't work.

Most likely, you are running under a different account than the current user.

> It seems that this program needs admin privilege to function properly (idk why it isn't set to run in that way by default)

No, it is specifically designed to avoid running elevated.

> and I can only get the autofill functions to work properly if I manually start the program and accept the admin prompt

That would be only in the portable version, the setup version uses UI Access to avoid elevation and work with any application weather is elevated or not.

> I'm using Windows 10 with latest update.

It is tested in W10 and W11.
