### ISSUE TITLE
"Error: Unknown Kdf" - Argon2 support seems missing

### ISSUE THREAD

**Issue by gitfiiisch** [anonymous1184/bitwarden-autotype#57]
After entering my master password, autotype crashes with the following error message:

![grafik](https://github.com/anonymous1184/bitwarden-autotype/assets/114433980/4e52b07e-b2d9-4c9e-b3c0-f75d8c32ecab)

'bw.js:13372 throw new Error("Unknown Kdf.") [...] at Crypto Service.'

I'm using Argon2id instead of the default PBKDF2 for the encryption key. Otherwise logging into my vault seemed to have worked fine (with API-Key). Autotype also downloaded -what I assume are - my encrypted password entries into the data.json file in APPDATA, just the decryption seems to fail.

I've use the pre-compiled installer setup.exe from the latest release.

**Comment by anonymous1184** [comment]
That is a Bitwarden error. The Autotype application only uses the passwords once the CLI tool delivers them, and never handles any of the information (passwords) or its encryption (all of that is offloaded to Bitwarden's own CLI application).

If you are using a CLI version that supports Argon2id you might want to try and delete the `data.json` file located in `%AppData%\Bitwarden Autotype` and perhaps that will solve the issue.

---

If you are using an old version of the CLI tool:

- Go to [github.com/bitwarden/clients][1].
- Download the latest `cli-v*` release ([v2023.7.0][2] as of today).
- Replace the `bw.exe` found in `C:\Program Files\Bitwarden Autotype`.
- Delete the `data.json` file in `%AppData%\Bitwarden Autotype`.

I know it is a hassle but, I haven't had time to push the new release that takes care of this (alongside a plethora of other QoL improvements and fixes, but "*it's on its way*" and I promise the yearlong wait will be worthwhile).

[1]: https://github.com/bitwarden/clients
[2]: https://github.com/bitwarden/clients/releases/tag/cli-v2023.7.0

**Comment by gitfiiisch** [comment]
It works!

I updated/replaced the bw.exe, as you said, and removed the data.json.

Thanks a lot!

**Comment by anonymous1184** [comment]
Glad it worked out!
