### ISSUE TITLE
Doesn't work with bitwarden.eu or other custom domain

### ISSUE THREAD

**Issue by mollwe** [anonymous1184/bitwarden-autotype#58]
Can't set which domain to login to. My vault is at bitwarden.eu but I guess it defaults to bitwarden.com and therefore the login attempt fails. 

Tried both with email address and personal api key.

![image](https://github.com/anonymous1184/bitwarden-autotype/assets/610738/d2f1bb0d-eed6-46c5-af8a-743a650b7754)
![image](https://github.com/anonymous1184/bitwarden-autotype/assets/610738/1e6ec938-569c-400b-be0c-5b0f71837627)

**Comment by KnightTim** [comment]
This is basically the same as #4, #29, #33, and #42

See #42 or #29 for instructions on how to change the server URL.
